---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - name: local-html-volume
          # This is where Nginx looks for files inside the container
          mountPath: /usr/share/nginx/html 
      volumes:
      - name: local-html-volume
        # hostPath mounts a directory from the host node into the pod
        hostPath:
          # ⚠️ Change this to the absolute path of the folder on your server
          path: /actions-runner/_work/Digitalxc-Coding-Challenge-Test_SRE/Digitalxc-Coding-Challenge-Test_SRE/nginx
          # DirectoryOrCreate ensures K3s creates the folder on the host if it doesn't exist
          type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: default
spec:
  type: ClusterIP # Keeps it safe internally. (Change to LoadBalancer if using an external cloud LB provider)
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: nginx

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ingress
  namespace: default
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nginx-service
            port:
              number: 80