name: Deploy changes to K3s

on:
  push:
    branches:
      - master # Triggers on every push to your master branch
    # paths:
    #   - 'k8s/**' # Optional: Only trigger if files inside the k8s folder change

jobs:
  deploy-nginx-to-k3s:
    # Crucial: This directs the workflow to run on your newly registered AWS instance
    runs-on: k3s 

    steps:
      # Step 1: Clone the updated code from GitHub onto the server workspace
      - name: Checkout Source Code
        uses: actions/checkout@v4

      # Step 2: Apply the updated manifest infrastructure changes
      - name: Apply Kubernetes Manifests
        run: |
          # Use the system's k3s kubectl wrapper to apply configurations safely
          # sudo k3s kubectl apply -f k8s/nginx-deployment.yml
          kubectl apply -f k8s/nginx-deployment.yml

      # Step 3: Optional Verify Rollout
      - name: Verify Deployment Rollout Status
        run: |
          sudo k3s kubectl rollout status deployment/nginx-deployment --timeout=60s